/**
 * Self-hosts the two typefaces CLAUDE.md specifies (Bricolage
 * Grotesque for display, Atkinson Hyperlegible for body). No CDN at
 * runtime: this downloads the LATIN woff2 subsets into public/fonts/
 * and regenerates src/fonts.css with @font-face rules pointing at
 * them. Rerun to refresh (Google bumps the file hashes occasionally):
 *
 *   node scripts/fetch-fonts.mjs
 *
 * Licenses (both redistributable, recorded in CREDITS.md):
 *   Bricolage Grotesque — SIL Open Font License 1.1
 *   Atkinson Hyperlegible — Atkinson Hyperlegible Font License (Braille Institute)
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { resolve } from 'node:path'

const CSS_URL =
  'https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,700&family=Atkinson+Hyperlegible:wght@400;700&display=swap'
// A modern browser UA is what makes Google serve woff2 instead of ttf.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const css = await (await fetch(CSS_URL, { headers: { 'User-Agent': UA } })).text()

// Keep only the plain-latin subsets — latin-ext/vietnamese/cyrillic
// would roughly triple the payload for glyphs this site never renders.
const LATIN = 'U+0000-00FF'
const blocks = css
  .split('@font-face')
  .slice(1)
  .map((b) => b.slice(0, b.indexOf('}') + 1))
  .filter((b) => b.includes(LATIN))

mkdirSync(resolve('public/fonts'), { recursive: true })

// Variable fonts serve the SAME file for every requested weight
// (Bricolage's 400 and 700 downloads are byte-identical), so faces are
// grouped per family and deduped by content: one file, a weight RANGE.
const faces = []
for (const block of blocks) {
  const family = /font-family: '([^']+)'/.exec(block)[1]
  const weight = Number(/font-weight: (\d+)/.exec(block)[1])
  const url = /url\((https:[^)]+)\)/.exec(block)[1]
  const range = /unicode-range: ([^;]+);/.exec(block)[1]
  const buf = Buffer.from(await (await fetch(url, { headers: { 'User-Agent': UA } })).arrayBuffer())
  const twin = faces.find((f) => f.family === family && f.buf.equals(buf))
  if (twin) twin.weights.push(weight)
  else faces.push({ family, weights: [weight], range, buf })
}

let out = `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand.
   Self-hosted latin subsets; see CREDITS.md for licenses. */\n`
let total = 0

for (const face of faces) {
  const lo = Math.min(...face.weights)
  const hi = Math.max(...face.weights)
  const base = face.family.toLowerCase().replace(/[^a-z]+/g, '-')
  const slug = `${base}-${lo === hi ? lo : 'var'}.woff2`
  writeFileSync(resolve('public/fonts', slug), face.buf)
  total += face.buf.length
  const weightCss = lo === hi ? `${lo}` : `${lo} ${hi}`
  console.log(`${slug} — ${(face.buf.length / 1024).toFixed(1)} KB (weight ${weightCss})`)
  out += `
@font-face {
  font-family: '${face.family}';
  font-style: normal;
  font-weight: ${weightCss};
  font-display: swap;
  src: url('/fonts/${slug}') format('woff2');
  unicode-range: ${face.range};
}
`
}

writeFileSync(resolve('src/fonts.css'), out)
console.log(`\n${faces.length} files, ${(total / 1024).toFixed(1)} KB total → src/fonts.css`)
